### ISSUE TITLE
Consolidate all YNAB converter scripts into just one?

### ISSUE THREAD

**Issue by torbengb** [rennes-us/ynab-convert#1]
Hello Rennes!
I've noticed that there are more than 80 GitHub projects related to YNAB converter scripts. Would it be helpful and would there be interest in an effort to consolidate all (most) of these into a single tool? On the plus side, clearly there's more than enough solutions and contributors. On the minus side, these are spread across different spoken languages, programming languages, and of course bank export formats.

You're probably familiar with the YNAB subreddit. I've posted this idea here for a joint discussion: https://www.reddit.com/r/ynab/comments/75fctx/tools_can_we_consolidate_all_our_ynab_import/

Greetings from Vienna,
Ben

**Comment by ressy** [comment]
It looks like [bank2ynab](https://github.com/bank2ynab/bank2ynab) has flourished since this idea started, so I'd still like to merge my converters in at some point, probably Shopify most of all.  (Wow, it's been over a year already?)  Thanks for all the effort on that.

**Comment by ressy** [comment]
I have a draft bank2ynab plugin for shopify that's working with the latest develop branch and the other converters here are doable via the config, so I'm archiving this repo (and will hopefully make a pull request at some point!)
